var musicSource=[
	{
		'music_name':'泡沫',
		'music_url':'music/paomo.mp3',
		'artist_name':'邓紫棋',
		'head_url':'img/singer/dengziqi.jpg',
		'lyric_url':'lrc/paomo.lrc'
	},
	{
		'music_name':'趁早',
		'music_url':'music/chenzao.mp3',
		'artist_name':'张惠妹',
		'head_url':'img/singer/zhanghuimei.jpg',
		'lyric_url':'lrc/chenzao.lrc'
	},
	{
		'music_name':'囚鸟',
		'music_url':'music/qiuniao.mp3',
		'artist_name':'邓紫棋',
		'head_url':'img/singer/dengziqi.jpg',
		'lyric_url':'lrc/qiuniao.lrc'
	},
	{
		'music_name':'逆光飞翔',
		'music_url':'music/niguangfeixiang.mp3',
		'artist_name':'范逸臣',
		'head_url':'img/singer/fanyichen.jpg',
		'lyric_url':'lrc/niguangfeixiang.lrc'
	},
	{
		'music_name':'未闻花名',
		'music_url':'music/weiwenhuaming.mp3',
		'artist_name':'口琴',
		'head_url':'img/singer/kouqin.jpg',
		'lyric_url':''
	},
	{
		'music_name':'失眠症',
		'music_url':'music/shimianzheng.mp3',
		'artist_name':'苏仨',
		'head_url':'img/singer/susan.jpg',
		'lyric_url':'lrc/shimianzheng.lrc'
	},
	{
		'music_name':'一万个舍不得',
		'music_url':'music/yiwangeshebude.mp3',
		'artist_name':'庄心妍',
		'head_url':'img/singer/zhuangxinyan.jpg',
		'lyric_url':'lrc/yiwangeshebude.lrc'
	}
]
